import duckdb,re
sql=open('/home/jianj/code/qp1-corpact/silver/08_silver_ohlcv_day_adjusted.sql').read()
m=re.search(r"CREATE OR REPLACE TEMP VIEW _resolved_splits AS.*?;",sql,re.S).group(0)
m=m.replace("bootcamp_students.evangoh_capstone.","")
f=re.search(r"CREATE OR REPLACE TEMP VIEW _split_factors AS.*?;",sql,re.S).group(0)
c=duckdb.connect()
c.execute("create table bronze_corporate_actions(symbol varchar,ex_date date,split_ratio double,source varchar,fetched_ts timestamp)")
c.execute("create table _deduped_daily as select 'AMZN' symbol, d::date event_date from generate_series(date '2022-06-01',date '2022-06-10',interval 1 day) t(d)")
c.execute("create table _universe as select 'AMZN' symbol")
def run(rows):
    c.execute("delete from bronze_corporate_actions")
    for r in rows: c.execute("insert into bronze_corporate_actions values(?,?,?,?,'2026-01-01')",r)
    c.execute(m); c.execute(f)
    return c.execute("select event_date,cumulative_split_ratio from _split_factors order by 1").fetchall()
print("same day:",run([('AMZN','2022-06-06',20.0,'massive'),('AMZN','2022-06-06',20.0,'yfinance')])[:2])
print("1-day off:",run([('AMZN','2022-06-06',20.0,'massive'),('AMZN','2022-06-03',20.0,'yfinance')]))
