command:
  - uvicorn
  - api.main:app
  - --host
  - 0.0.0.0
  - --port
  - "${DATABRICKS_APP_PORT:-8000}"

env:
  - name: CATALOG
    value: bootcamp_students
  - name: SCHEMA
    value: evangoh_capstone
