resources:
  apps:
    quant_platform:
      name: quant-platform-${bundle.target}
      description: Quant Platform API and web application.
      source_code_path: ..
      config:
        command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
        env:
          - name: CATALOG
            value: bootcamp_students
          - name: SCHEMA
            value: ${var.schema}
          - name: DATABRICKS_WAREHOUSE_ID
            value: b15d3d6f837ba428
      resources:
        - name: lakebase
          database:
            instance: evangoh-capstone-lakebase
            permission: CAN_CONNECT_AND_CREATE
        - name: sql_warehouse
          sql_warehouse:
            id: b15d3d6f837ba428
            permission: CAN_USE